### PR TITLE
Fix AR config issues [fixes #72]

### LINKED ISSUE #72: ActiveRecord not configured correctly
Hi,

I have some problem about `ActiveRecord::Base.belongs_to_required_by_default` config.

According the issue https://github.com/rails/rails/issues/27777 and https://github.com/rails/rails/issues/23589#issuecomment-229247727, this problem needs to resolved by gem.

Is there have any plan to fix it?

### PR DESCRIPTION
**Pull request by kratob**
When active_type is used inside Rails it loads `ActiveRecord::Base` too early. This causes configuration settings set via `Rails.application.config.active_record` (for example `Rails.application.config.belongs_to_required_by_default = true`) set in a Rails initializer (as is default in Rails 5) to be disregarded.

In case `ActiveType` is used without `Rails`, we should load regularly.

### CODE REVIEW

**Comment by kratob** [comment]
See https://github.com/rails/rails/issues/23589 for the underlying issue and https://github.com/plataformatec/devise/commit/c2c74b0a39238e7d997486814a1c8f75fdaf276f for how Devise fixed it.

**Comment by kratob** [comment]
@henning-koch Does this look like a sensible solution to you?

File: lib/active_type.rb [hunk 1]
```diff
@@ -1,14 +1,31 @@
...
-require 'active_type/util'
-require 'active_type/record'
-require 'active_type/object'
-
-if ActiveRecord::VERSION::STRING == '4.2.0'
-  raise(<<-MESSAGE.strip_heredoc)
-    ActiveType is not compatible with ActiveRecord 4.2.0. Please upgrade to 4.2.1
-    For details see https://github.com/makandra/active_type/issues/31
-  MESSAGE
+
```
Comment (henning-koch) [inline lib/active_type.rb]: Should we require `active_support/all` here, since we're no longer lettering `active_record` do it for us?

File: lib/active_type.rb [hunk 2]
```diff
@@ -1,14 +1,31 @@
...
+  if ActiveRecord::VERSION::STRING == '4.2.0'
+    raise(<<-MESSAGE.strip_heredoc)
+      ActiveType is not compatible with ActiveRecord 4.2.0. Please upgrade to 4.2.1
+      For details see https://github.com/makandra/active_type/issues/31
+    MESSAGE
+  end
+end
+
+
+if defined?(Rails) && defined?(ActiveSupport)
```
Comment (henning-koch) [inline lib/active_type.rb]: ... then we could drop the `defined?(ActiveSupport)`  check here.

Do other affected gems check the case using `defined?(Rails)` as well?

File: lib/active_type.rb (hunk 1 above)
Comment (kratob) [inline lib/active_type.rb]: I don't want to load more of `active_support` than we absolutely need, and we haven't require `active_support/all` in the past (and I doubt `active_record` does it either).

File: lib/active_type.rb (hunk 2 above)
Comment (kratob) [inline lib/active_type.rb]: I suspect the check is unnecessary anways, since you probably cannot have `Rails` but not `ActiveSupport`. This was more paranoia.

I'm not sure what other gems do. I've just seen the Devise solution, but that's a different case, since Devise does not work without Rails anyways. I don't want users to have to require `active_record` manually in case they don't use Rails.

**Comment by henning-koch** [comment]
OK, let's release it.
